spring:
  datasource:
    url: jdbc:postgresql://10.11.1.62:5430/firstapi
    username: postgres
    password: benny100
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: beca-service
  profiles:
    active: dev

server:
  port: 5050

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://gatewayservice:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
